"""ShieldCortex Python SDK — AI memory security scanning.

Usage:
    from shieldcortex import ShieldCortex

    client = ShieldCortex(api_key="sc_live_...")
    result = client.scan("user input here")

    if not result.allowed:
        print(f"Blocked: {result.firewall.reason}")
"""

from shieldcortex._version import __version__
from shieldcortex.async_client import AsyncShieldCortex
from shieldcortex.client import ShieldCortex
from shieldcortex.errors import (
    AuthError,
    ForbiddenError,
    NotFoundError,
    RateLimitError,
    ShieldCortexError,
    ValidationError,
)
from shieldcortex.types import (
    AlertRule,
    AuditEntry,
    AuditIngestEntry,
    AuditIngestResponse,
    AuditQuery,
    AuditResponse,
    AuditStats,
    BatchItem,
    BatchResult,
    CheckoutResponse,
    CreateKeyResponse,
    CreateWebhookResponse,
    DeleteVerificationResponse,
    DetectedThreat,
    Device,
    ExportManifest,
    ExportManifestDetail,
    ExportManifestListResponse,
    ExportVerificationEvent,
    ExportVerificationListResponse,
    ExportVerifyExpected,
    ExportVerifyResponse,
    ExportVerifyResult,
    FirewallResult,
    FirewallRule,
    FragmentationResult,
    IncidentCoverage,
    IncidentEvent,
    IncidentReplayResponse,
    IncidentStreamSummary,
    InjectionPattern,
    InjectionPatternsResponse,
    Invite,
    InviteListResponse,
    IronDomeEvent,
    IronDomeEventsResponse,
    IronDomePoliciesResponse,
    IronDomePolicy,
    IronDomeStats,
    IronDomeTopDevice,
    KeyInfo,
    KeyListItem,
    KeyListResponse,
    LicenseInfo,
    ManifestVerification,
    MembersResponse,
    Pagination,
    PatternSyncItem,
    PatternSyncResponse,
    PatternTestResult,
    PolicySyncResponse,
    PortalResponse,
    QuarantineItem,
    QuarantineQuery,
    QuarantineResponse,
    RecallExplainResponse,
    RecallLinkedEntity,
    RecallMemory,
    RecallResult,
    RecallScoreBreakdown,
    RegenerateLicenseResponse,
    ReviewResponse,
    ScanConfig,
    ScanResult,
    ScanSource,
    SensitivityResult,
    SkillFinding,
    SkillIngestResponse,
    SkillScanFile,
    SkillScanListResponse,
    SkillScanMetadata,
    SkillScanResult,
    SkillThreat,
    SourceCount,
    SyncDeviceHealth,
    SyncedMemoriesResponse,
    SyncedMemory,
    SyncedSkillScan,
    SyncGraphEntity,
    SyncGraphResponse,
    SyncGraphTriple,
    SyncHealth,
    SyncHealthSummary,
    SyncLatestDeviceSync,
    SyncMemory,
    SyncMemoryEntityLink,
    SyncMemorySummary,
    SyncPushResponse,
    TeamInfo,
    TeamMember,
    TestWebhookResponse,
    ThreatReportResponse,
    TrendBucket,
    TrendResponse,
    TrustResult,
    UsageBreakdown,
    UsageInfo,
    UsageResponse,
    VerificationDayStats,
    VerificationDetail,
    VerificationListItem,
    VerificationListResponse,
    VerificationQuota,
    VerificationResult,
    VerificationStats,
    Webhook,
    WebhookDelivery,
)

__all__ = [
    "__version__",
    # Clients
    "ShieldCortex",
    "AsyncShieldCortex",
    # Errors
    "ShieldCortexError",
    "AuthError",
    "RateLimitError",
    "ValidationError",
    "NotFoundError",
    "ForbiddenError",
    # Scan types
    "ScanSource",
    "ScanConfig",
    "ScanResult",
    "FirewallResult",
    "SensitivityResult",
    "TrustResult",
    "FragmentationResult",
    "UsageInfo",
    "BatchItem",
    "BatchResult",
    "SkillThreat",
    "SkillScanMetadata",
    "SkillScanResult",
    # Audit types
    "AuditQuery",
    "AuditEntry",
    "AuditResponse",
    "AuditStats",
    "SourceCount",
    "TrendBucket",
    "TrendResponse",
    "Pagination",
    # Quarantine types
    "QuarantineQuery",
    "QuarantineItem",
    "QuarantineResponse",
    "ReviewResponse",
    # Key types
    "KeyInfo",
    "CreateKeyResponse",
    "KeyListItem",
    "KeyListResponse",
    # Team types
    "TeamInfo",
    "TeamMember",
    "MembersResponse",
    "UsageBreakdown",
    "UsageResponse",
    # Invite types
    "Invite",
    "InviteListResponse",
    # Billing types
    "CheckoutResponse",
    "PortalResponse",
    # Device types
    "Device",
    # Alert types
    "AlertRule",
    # Webhook types
    "Webhook",
    "CreateWebhookResponse",
    "WebhookDelivery",
    "TestWebhookResponse",
    # Firewall types
    "FirewallRule",
    # Iron Dome types
    "InjectionPattern",
    "InjectionPatternsResponse",
    "PatternSyncItem",
    "PatternSyncResponse",
    "PatternTestResult",
    "IronDomePolicy",
    "IronDomePoliciesResponse",
    "PolicySyncResponse",
    # Verification types
    "DetectedThreat",
    "VerificationResult",
    "VerificationListItem",
    "VerificationListResponse",
    "VerificationDetail",
    "VerificationDayStats",
    "VerificationQuota",
    "VerificationStats",
    "DeleteVerificationResponse",
    # Skill sync types
    "SkillFinding",
    "SkillScanFile",
    "SkillIngestResponse",
    "SyncedSkillScan",
    "SkillScanListResponse",
    # Threat types
    "ThreatReportResponse",
    # Incident types
    "IncidentEvent",
    "IncidentStreamSummary",
    "IncidentCoverage",
    "IncidentReplayResponse",
    # Recall types
    "RecallMemory",
    "RecallLinkedEntity",
    "RecallScoreBreakdown",
    "RecallResult",
    "RecallExplainResponse",
    # Sync types
    "SyncHealth",
    "SyncMemory",
    "SyncPushResponse",
    "SyncedMemory",
    "SyncLatestDeviceSync",
    "SyncDeviceHealth",
    "SyncHealthSummary",
    "SyncMemorySummary",
    "SyncedMemoriesResponse",
    "SyncGraphEntity",
    "SyncGraphTriple",
    "SyncMemoryEntityLink",
    "SyncGraphResponse",
    # License types
    "LicenseInfo",
    "RegenerateLicenseResponse",
    # Audit Iron Dome & export types
    "IronDomeTopDevice",
    "IronDomeStats",
    "IronDomeEvent",
    "IronDomeEventsResponse",
    "AuditIngestEntry",
    "AuditIngestResponse",
    "ExportManifest",
    "ExportManifestListResponse",
    "ManifestVerification",
    "ExportManifestDetail",
    "ExportVerifyResult",
    "ExportVerifyExpected",
    "ExportVerifyResponse",
    "ExportVerificationEvent",
    "ExportVerificationListResponse",
]
